// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentAuthor } from "./CommentAuthor";

export interface Comment { id: bigint, author: CommentAuthor, parentId: bigint | null, toUserId: bigint | null, content: string, createdAt: string, modifiedAt: string, replyCount: bigint, }