// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExploreMode } from "./ExploreMode";
import type { Language } from "./Language";

export interface ExploreQuery { query: string | null, mode: ExploreMode | null, language: Language | null, }