// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontPageCuratedProject } from "./FrontPageCuratedProject";
import type { FrontPageDesignStudioProject } from "./FrontPageDesignStudioProject";
import type { FrontPageFeaturedStudio } from "./FrontPageFeaturedStudio";
import type { FrontPageMostRemixedProject } from "./FrontPageMostRemixedProject";
import type { FrontPageProject } from "./FrontPageProject";

export interface FrontPage { newProjects: Array<FrontPageProject>, featuredStudios: Array<FrontPageFeaturedStudio>, featuredProjects: Array<FrontPageProject>, curatedProjects: Array<FrontPageCuratedProject>, mostRemixedProjects: Array<FrontPageMostRemixedProject>, mostLovedProjects: Array<FrontPageProject>, designStudioProjects: Array<FrontPageDesignStudioProject>, }