// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FrontPageProject { title: string, authorName: string, id: bigint, loveCount: number, }