// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface FrontPageMostRemixedProject { id: bigint, title: string, remixCount: number, loveCount: number, authorName: string, }