// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthSqlItemItem } from "./HealthSqlItemItem";

export interface HealthSqlItem { primary: HealthSqlItemItem, replica: HealthSqlItemItem, }