// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthSqlItem } from "./HealthSqlItem";

export interface HealthSql { main: HealthSqlItem, projectComments: HealthSqlItem, studioComments: HealthSqlItem, profileComments: HealthSqlItem, }