// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthCache } from "./HealthCache";
import type { HealthSql } from "./HealthSql";

export interface Health { version: string, uptime: number, load: Array<number>, sql: HealthSql, timeStamp: bigint, cache: HealthCache, }