// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageCommentLocation = { is: "profile", id: bigint, name: string, } | { is: "project", id: bigint, title: string, } | { is: "studio", id: bigint, title: string, };