// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageEvent } from "./MessageEvent";

export interface Message { id: bigint, createdAt: string, actorName: string, actorId: bigint, event: MessageEvent, }