// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface News { id: bigint, at: string, title: string, url: string, description: string, }