// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAuthor } from "./ProjectAuthor";
import type { ProjectStats } from "./ProjectStats";

export interface Project { author: ProjectAuthor, id: bigint, title: string, description: string, instructions: string, visibility: string, public: boolean, commentsAllowed: boolean, isPublished: boolean, stats: ProjectStats, token: string, }