// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAuthor } from "./ProjectAuthor";
import type { ProjectHistory } from "./ProjectHistory";
import type { ProjectRemix } from "./ProjectRemix";
import type { ProjectStats } from "./ProjectStats";

export interface Project2 { id: bigint, title: string, description: string, instructions: string, visibility: string, public: boolean, commentsAllowed: boolean, isPublished: boolean, author: ProjectAuthor, stats: ProjectStats, remix: ProjectRemix, history: ProjectHistory, }