// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProjectStats { loves: bigint, views: bigint, favorites: bigint, remixes: bigint, }