// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserHistory } from "./UserHistory";

export interface ProjectAuthor { name: string, id: bigint, scratchTeam: boolean, history: UserHistory, }