// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExploreMode } from "./ExploreMode";

export interface SearchQuery { mode: ExploreMode | null, query: string | null, }