// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SendComment { content: string, parentId: bigint | null, toId: bigint | null, }