// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudioHistory } from "./StudioHistory";

export interface Studio2 { id: bigint, title: string, host: bigint, description: string, visibility: string, public: boolean, openToAll: boolean, commentsAllowed: boolean, history: StudioHistory, }