// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StudioActionEvent } from "./StudioActionEvent";

export interface StudioAction { id: bigint, actorName: string, actorId: bigint, createdAt: string, event: StudioActionEvent, }