// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StudioActionEvent = { is: "update" } | { is: "addProject", id: bigint, title: string, } | { is: "removeProject", id: bigint, title: string, } | { is: "acceptInvite", from_name: string, } | { is: "promote", name: string, };