// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StudioProject { id: bigint, title: string, name: string, actorId: bigint, creatorId: bigint, }