// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StuffAuthor } from "./StuffAuthor";

export interface StuffProjectFields { author: StuffAuthor, createdAt: string, modifiedAt: string, sharedAt: string | null, favoriteCount: number, public: boolean, loveCount: number, remixCount: number, title: string, viewCount: number, visibility: string, commentersCount: bigint, }