// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StuffAuthor } from "./StuffAuthor";

export interface StuffStudioFields { commentersCount: bigint, curatorCount: number, createdAt: string, modifiedAt: string, owner: StuffAuthor, projectsCount: number, title: string, }