// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StuffStudioFields } from "./StuffStudioFields";

export interface StuffStudio { fields: StuffStudioFields, id: bigint, }