// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeaturedLabel } from "./FeaturedLabel";
import type { UserFeaturedProfile } from "./UserFeaturedProfile";
import type { UserFeaturedProject } from "./UserFeaturedProject";

export interface UserFeatured { id: bigint, label: FeaturedLabel, project: UserFeaturedProject, profile: UserFeaturedProfile, }