// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserCommentContentFragment = { is: "link", to: string, content: string, } | { is: "text", content: string, } | { is: "emoji", to: string, };