// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UserFeaturedProject { authorName: string, id: bigint, title: string, modifiedAt: string, }