// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserHistory } from "./UserHistory";

export interface User { scratchTeam: boolean, id: bigint, bio: string, status: string, country: string, history: UserHistory, name: string, }